import HorizontalScroll from "react-horizontal-scrolling";

const playground = () => {
  return (
    <>
    <h1>HELLO</h1>
    <HorizontalScroll>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
      <div>aaaaaaaaaa</div>
    </HorizontalScroll>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    <h1>HELLO</h1>
    </>
  );
};

export default playground;
